version: 2
jobs:
  test:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t gengjiawen/android-ndk:$CIRCLE_BRANCH .
      - run:
          name: docker info
          command: |
            docker run --rm --name rn-env gengjiawen/android-ndk bash -c "npm i -g envinfo && envinfo"

workflows:
  version: 2
  perfs:
    jobs:
      - test
