version: 2
jobs:
  test:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t gengjiawen/android-ndk:$CIRCLE_BRANCH .
      - run:
          name: Docker info
          command: |
            docker run --rm --name rn-env gengjiawen/android-ndk:$CIRCLE_BRANCH bash -c "npm i -g envinfo && envinfo"
      - run:
          name: Publish Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gengjiawen/android-ndk:$CIRCLE_BRANCH

workflows:
  version: 2
  perfs:
    jobs:
      - test
